# Generated by Django 3.1.1 on 2021-01-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to='profile/avatars/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
